const UserRouter = require("./UserRouter");
const productsRouter = require("./products.route");
const ShipperRouter = require("./shipperRouter");
const orderRouter = require("./orderRouter");
const customerRouter = require("./customerRouter");
const importReceiptRoute = require("./importReceiptRoute");
const importDetailRoutes = require("./importDetailRoutes");
const suppliersRouter = require("./supplierRouter");
const exportDetailRoutes = require("./exportDetailRoutes");
const exportReceiptRoutes = require("./exportReceiptRoutes");
const inventoryRouter = require("./inventoryRouter");
const stockRouter = require("./stockRouter");
const statisticsRouter = require('./statisticsRouter');
const routes = (app) => {
  app.use("/api/v1/user", UserRouter);
  app.use("/api/v1/shipper", ShipperRouter);
  app.use("/api/v1/products", productsRouter);
  app.use("/api/v1/orders", orderRouter);
  app.use("/api/v1/customer", customerRouter);
  app.use("/api/v1/import-receipt", importReceiptRoute);
  app.use("/api/v1/import-detail", importDetailRoutes);
  app.use("/api/v1/suppliers", suppliersRouter);
  app.use("/api/v1/export-detail", exportDetailRoutes);
  app.use("/api/v1/export-receipt", exportReceiptRoutes);
  app.use("/api/v1/inventory", inventoryRouter);
  app.use("/api/v1/stock", stockRouter);
  app.use("/api/v1/statistics", statisticsRouter);
};
module.exports = routes;
